/*!
 * tree component
 * http://www.wadecn.com/
 * auth:xiedx@asiainfo-linkage.com
 * Copyright 2011, WADE
 */
(function(a){if(typeof(a.tree)=="undefined"){a.tree=function(c,b){return new a.tree.fn.construct(c,b);};a.tree.fn={construct:function(c,b){this.id=c;this.params={};this.queue=[];a.extend(this,b);
},setParam:function(b,c){this.params[b]=c;},setup:function(b){if(b&&a.isPlainObject(b)){a.extend(this,b);}},buildParams:function(){var c=[];c.push("Tree_ID="+encodeURIComponent(this.id));c.push("Tree_IsShowCheckBox="+this.isShowCheckBox);c.push("Tree_IsSearch="+this.isSearch);c.push("Tree_IsFolder="+this.isFolder);
c.push("Tree_IsAsync="+this.isAsync);if(this.checkBoxName){c.push("Tree_CheckBoxName="+encodeURIComponent(this.checkBoxName));}if(this.checkBoxType){c.push("Tree_CheckBoxType="+encodeURIComponent(this.checkBoxType));}if(this.iconDir){c.push("Tree_IconDir="+encodeURIComponent(this.iconDir));}if(!a.isEmptyObject(this.params)){for(var b in this.params){c.push(encodeURIComponent(b)+"="+encodeURIComponent(this.params[b]));
}}return c.join("&");},getNodeDataByDataId:function(f,c){if(!f||!a.isString(f)){return;}if(!c||!a.isString(c)){return;}var b=c.split("●");var g=window["treeData_"+f];if(g&&a.isObject(g)&&b&&b.length){var e,h;for(var d=0;d<b.length;d++){if(d==0){e=g[b[d]];}else{if(e){h=e["childNodes"];if(h&&a.isObject(h)){e=h[b[d]];
}}}if(!e){break;}}return e;}},getParentNodeDataByDataId:function(d,c){if(!d||!a.isString(d)){return;}if(!c||!a.isString(c)){return;}var b=c.split("●");if(b&&b.length>=2){b.splice(b.length-1,1);return a.tree.fn.getNodeDataByDataId(d,b.join("●"));}},getNodeDataByNodeId:function(e){if(!e||!a.isString(e)){return;
}var c=e.lastIndexOf("○");var d=e.substring(0,c);var b=e.substring(c+1,e.length);return a.tree.fn.getNodeDataByDataId(d,b);},getTreeNodeIdByNodeId:function(d){if(!d||!a.isString(d)){return;}var b=this.getDataIdByNodeId(d);var c=b.lastIndexOf("●");return b.substring(c+1,d.length);},getDataIdByNodeId:function(c){if(!c||!a.isString(c)){return;
}var b=c.lastIndexOf("○");return c.substring(b+1,c.length);},getTreeIdByNodeId:function(d){if(!d||!a.isString(d)){return;}var b=d.lastIndexOf("○");var c=d.substring(0,b);return c;},getCheckedNodeIds:function(g,f){if(a.isBoolean(g)){f=g;g=this.id;}else{if(undefined==g){g=this.id;}}if(!g){return;}var c=window[g];
if(!c.isShowCheckBox){return;}var d=[];a("#"+g+"_ct input[name="+c.checkBoxName+"]:checked").each(function(){d.push(a.attr(this.parentNode,"id"));});if(d.length>1&&f){d.sort(function(j,i){return j.lastIndexOf("●")-i.lastIndexOf("●");});var b,h;for(var e=d.length-1;e>-1;e--){if(!(b=a.tree.fn.getDataIdByNodeId(d[e]))){continue;
}h=a.tree.fn.getParentNodeDataByDataId(g,b);if(h&&a.inArray(g+"○"+h.dataid,d)>-1){d.splice(e,1);}}}return d;},buildNode:function(h,j){var m=window[h];if(!m){return;}var k=[];if(j&&a.isObject(j)){var f=j["dataid"];var d=h+"○"+f;var i=("true"==(""+j["haschild"]));var e=("true"==(""+j["complete"]));var c=j["href"];
var l=i?"fold":"file";k.push('<li id="'+d+'" class="'+l+'">\n');k.push('<a href="#nogo" class="ico"></a>\n');if("true"==j["showcheck"]){k.push('<input name="'+m.checkBoxName+'" type="'+(m.checkBoxType=="radio"?"radio":"checkbox")+'" class="e_checkbox" value="'+j["value"]+'" '+("true"==(""+j["checked"])?"checked":"")+" "+("true"==(""+j["disabled"])?"disabled":"")+" />\n");
}var b="text";var g=("true"==(""+j["isnew"]));if(g){b+=" new";}k.push('<a href="#nogo" class="'+b+'">'+j["text"]+"</a>\n");if(i){k.push("<ul></ul>");}k.push("</li>\n");}return k.join("");},bindNodeEvent:function(b){if(!b||!b.length){return;}b.children().each(function(){if(a.nodeName(this,"li")){a("a[class=ico]:first",this).bind("click",a.tree.fn.events.onIcoClick);
a("input[type=checkbox]:first,input[type=radio]:first",this).bind("click",a.tree.fn.events.onCheckBoxClick);a("a[class^=text]:first",this).bind("click",a.tree.fn.events.onTextClick);}});type=null;},unBindNodeEvent:function(b){if(!b||!b.length){return;}b.children().each(function(){if(a.nodeName(this,"li")){a("a[class=ico]:first",this).unbind("click",a.tree.fn.events.onIcoClick);
a("input[type=checkbox]:first,input[type=radio]:first",this).unbind("click",a.tree.fn.events.onCheckBoxClick);a("a[class^=text]:first",this).unbind("click",a.tree.fn.events.onTextClick);}});type=null;},init:function(){var d=this.id;var c=this;c.data=window["treeData_"+d];var b=a("#"+d+"_ct");if(!b.hasClass("c_tree")){b.addClass("c_tree");
b.addClass("c_tree-noborder");}var f=this.expandPath;if(!c.data){if(!this.clazz&&!this.method&&!this.listener&&!this.componentId){alert(a.lang.get("view.web.comp.tree.tip"));return;}b.append('<a id="'+d+'_loading" class="text loading">'+a.lang.get("view.web.comp.tree.loading")+"</a>");function e(h){var g=h.context;
if("0"!=g.x_resultcode){a("#"+d+"_loading").remove();alert(a.lang.get("view.web.comp.tree.failload",d)+g.x_resultinfo);}else{c.data=window["treeData_"+d]=h.data;if(a.isObject(window["treeData_"+d])){a("#"+d+"_loading").remove();window[d].draw();if(f&&a.isString(f)){window[d].expandByPath(f);}c.triggerInitAfterAction();
}}}if(this.clazz&&this.method){a.httphandler.post(this.clazz,this.method,this.buildParams(),e,null,{dataType:"json",simple:true});}else{a.ajax.post((this.page?this.page:null),this.listener,this.buildParams(),(this.componentId?this.componentId:null),e,null,{dataType:"json",simple:true});}}else{window[d].draw();
if(f&&a.isString(f)){window[d].expandByPath(f);}this.triggerInitAfterAction();}},empty:function(c){c=(c&&true==c);var e=this.id;if(!e){return;}var f=window["treeData_"+e];if(!f){return;}var d,b,g;b=a("#"+e+"_ct ul:first");a.tree.fn.unBindNodeEvent(b);for(var h in f){if(!c){f[h].complete="false";}a.tree.fn.emptyNode(e,f[h].dataid,c);
}a("#"+e+"_ct").empty();if(c){delete this.data;this.data=null;window["treeData_"+e]=null;}if(a.browser.msie){CollectGarbage();}},emptyNode:function(g,b,d){if(!g||!a.isString(g)){return;}var f=g+"○"+b;var c=a("#"+f+" ul:first");a.tree.fn.unBindNodeEvent(c);c.children().each(function(){if(a.nodeName(this,"li")){a("a[class=ico]:first",this).remove();
a("input[type=checkbox]:first,input[type=radio]:first",this).remove();a("a[class^=text]:first",this).remove();}});var e=a.tree.fn.getNodeDataByDataId(g,b);if(e){var h=e.childNodes;if(h&&!a.isEmptyObject(h)){for(var i in h){if(!d){h[i].complete="false";}a.tree.fn.emptyNode(g,h[i].dataid,d);}}}},draw:function(){var e=this.id;
if(this.data){var c=[];c.push("<ul>\n");var b=[];for(var f in this.data){if(this.data[f]&&a.isObject(this.data[f])){b.push([f,this.data[f].order]);}}b.sort(function(h,g){return parseInt(h[1])-parseInt(g[1]);});for(var d=0;d<b.length;d++){c.push(a.tree.fn.buildNode(e,this.data[b[d][0]]));}b=null;c.push("</ul>\n");
a("#"+this.id+"_ct").html(c.join(""));a.tree.fn.bindNodeEvent(a("#"+this.id+"_ct ul:first"));}},expand:function(b){var g=a.tree.fn.getTreeIdByNodeId(b);var l=a.tree.fn.getNodeDataByNodeId(b);if(!g||!l){return;}if("true"==(""+l["haschild"])&&"false"==(""+l["complete"])){var n=window[g];if(n.isAsync&&n.asyncLoading){alert(a.lang.get("view.web.comp.tree.loadnow"));
return;}a("#"+b+" a[class^=text]:first").addClass("loading");var k=[];var m;if(n.isAsync&&!l["childNodes"]){var d=n.buildParams();d+="&Tree_Parent_NodeID="+encodeURIComponent(l["id"]);d+="&Tree_Parent_DataID="+encodeURIComponent(l["dataid"]);d+="&Tree_Parent_GroupID="+encodeURIComponent(l["groupid"]);
d+="&Tree_Parent_isChecked="+encodeURIComponent(l["checked"]);n.asyncLoading=true;function e(i){return function(r){var t=a.tree.fn.getTreeIdByNodeId(i);var p=a.tree.fn.getNodeDataByNodeId(i);if(t){window[t].asyncLoading=false;}var q=r.context;if("0"!=q.x_resultcode){window[t].queue.length=0;a("#"+b+" a[class^=text]:first").removeClass("loading");
alert(a.lang.get("view.web.comp.tree.error",t,q.x_resultcode,q.x_resultinfo));}else{if(r.data&&a.isObject(r)){var o=window[t].queue;if(o.length){for(var s=o.length-1;s>=0;s--){if(o[s]==i){o.splice(s,1);}}}if(p){p["childNodes"]=r.data;a.tree.fn.expand(i);return;}}a("#"+b+" a[class^=text]:first").removeClass("loading");
}if(a.browser.msie){CollectGarbage();}};}if(n.clazz&&n.method){a.httphandler.post(n.clazz,n.method,d,e(b),null,{dataType:"json",simple:true});}else{a.ajax.post((n.page?n.page:null),n.listener,d,(n.componentId?n.componentId:null),e(b),null,{dataType:"json",simple:true});}return;}else{m=l["childNodes"];
}if(m&&a.isObject(m)){var c=[];for(var j in m){if(m[j]&&a.isObject(m[j])){c.push([j,m[j].order]);}}c.sort(function(o,i){return parseInt(o[1])-parseInt(i[1]);});for(var f=0;f<c.length;f++){k.push(a.tree.fn.buildNode(g,m[c[f][0]]));}c=null;var h=a("#"+b+" ul:first");h.html(k.join(""));a.tree.fn.bindNodeEvent(h);
a("#"+b+" a[class^=text]:first").removeClass("loading");l["complete"]="true";}else{alert(a.lang.get("view.web.comp.tree.nochild"));a("#"+b+" a[class^=text]:first").removeClass("loading");}}a("#"+b).removeClass("fold");a("#"+b).addClass("unfold");if(a.browser.msie){CollectGarbage();}},reloadData:function(e){if(!e){return;
}for(var b in e){var d=("true"==(""+e[b]["complete"]));if(d){e[b]["complete"]="false";var c=("true"==(""+e[b]["haschild"]));if(c&&e[b]["childNodes"]){this.reloadData(e[b]["childNodes"]);}}}},bindData:function(f,d){var e=a.tree.fn.getTreeIdByNodeId(f);var b=a.tree.fn.getNodeDataByNodeId(f);if(!b||!d){return;
}var c=("true"==(""+b["haschild"]));if(b["childNodes"]){this.reloadData(b["childNodes"]);a.extend(b["childNodes"],d);}else{b["childNodes"]=d;}if(!c){a("#"+f).append("<ul></ul>");a("#"+f).attr("class","fold");b["haschild"]="true";}b["complete"]="false";a.tree.fn.expand(f);},expandQueue:function(c){var b=window[c];
if(!b){return;}if(b.queue.length){if(!b.asyncLoading){b.expand(b.queue[0]);}b.timer=setTimeout("$.tree.fn.expandQueue('"+c+"');",500);}else{if(b.timer){clearTimeout(b.timer);}}},expandByPath:function(f,h,g){if(arguments.length==1){h=f;f=this.id;}else{if(arguments.length==2){g=h;h=f;f=this.id;}}if(!f||!a.isString(f)){alert("expandByPath:"+a.lang.get("view.web.comp.tree.noobj"));
return;}if(!h||!a.isString(h)){alert("expandByPath:"+a.lang.get("view.web.comp.tree.notnull"));return;}if(!g||!a.isString(g)){g="-";}var c=window[f];if(c){var d=h.split(g);var b=[];var j;for(var e=0;e<d.length;e++){b.push(d[e]);j=c.id+"○"+b.join("●");if(c.isAsync){c.queue.push(j);}else{a.tree.fn.expand(j);
}}if(c.isAsync){a.tree.fn.expandQueue(c.id);}}else{alert("expandByPath:"+a.lang.get("view.web.comp.tree.noobj"));}},collapse:function(d){var c=a.tree.fn.getTreeIdByNodeId(d);var b=a.tree.fn.getNodeDataByNodeId(d);if(!c||!b){return;}a("#"+d).removeClass("unfold");a("#"+d).addClass("fold");},triggerNode:function(c){if(!c){return;
}var b=a("#"+c).hasClass("unfold");if(b){a.tree.fn.collapse(c);}else{a.tree.fn.expand(c);}},clickNode:function(f){var e=a.tree.fn.getTreeIdByNodeId(f);var d=a.tree.fn.getNodeDataByNodeId(f);if(!d){return;}var b=window[e];if(!b.isShowCheckBox){return;}if("true"!=(""+d["haschild"])){if(b.lastClickNodeId){a("#"+b.lastClickNodeId+" a[class^=text]").removeClass("on");
}a("#"+f+" a[class^=text]").addClass("on");b.lastClickNodeId=f;if("true"==d["showcheck"]){var c=a("#"+f+" input[type!=text]:first");if(c.length){c.data("text_trigger",true);c.trigger("click");}}}},checkNode:function(h,p,g){var f=a.tree.fn.getTreeIdByNodeId(h);var q=a.tree.fn.getNodeDataByNodeId(h);if(!q){return;
}if(!window[f]){return;}if(!window[f].isShowCheckBox){return;}var j=window[f].checkBoxType;var t,l=q.checked;if("radio"==j){q.checked="true";var r=window[f].lastCheckedNodeId;if(r&&r!=h){var m=a.tree.fn.getNodeDataByNodeId(r);if(m){m.checked="false";}}}else{if("checkbox"==j){t=g?g:(l=="true"?"false":"true");
q.checked=t;if(p){}else{a("#"+h+" input[type=checkbox]:first").attr("checked","true"==t?true:false);}if("true"==q.haschild){var d=q["childNodes"];if(d&&a.isObject(d)){var b,k;for(var n in d){k=d[n];if(a.isObject(k)){b=f+"○"+k.dataid;setTimeout("$.tree.fn.checkNode('"+b+"',false,'"+t+"')",0);}}}}var c,e,i,o;
i=q.id;o=q.dataid;while(c=a.tree.fn.getParentNodeDataByDataId(f,o)){e=f+"○"+c.dataid;if("false"==t){c.checked="false";a("#"+e+" input[type!=text]:first").attr("checked",false);}else{if("true"==t){var s=true;var d=c["childNodes"];var k;if(d&&a.isObject(d)){for(var n in d){k=d[n];if(i!=k.id&&"true"!=k.checked){s=false;
break;}}}if(s){c.checked="true";a("#"+e+" input[type!=text]:first").attr("checked",true);}}}i=c.id;o=c.dataid;}}}window[f].lastCheckedNodeId=h;},triggerCheckBoxAction:function(d){var c=a.tree.fn.getNodeDataByNodeId(d);var b=a.tree.fn.getTreeIdByNodeId(d);if(this.checkBoxAction&&a.isString(this.checkBoxAction)){return new Function("var nodedata=arguments[0];var treeid=arguments[1];return "+this.checkBoxAction)(c,b);
}return true;},triggerTextAction:function(d){var c=a.tree.fn.getNodeDataByNodeId(d);var b=a.tree.fn.getTreeIdByNodeId(d);if(this.textAction&&a.isString(this.textAction)){return new Function("var nodedata=arguments[0];var treeid=arguments[1];return "+this.textAction)(c,b);}return true;},triggerInitAfterAction:function(){if(this.initAfterAction){if(a.isString(this.initAfterAction)){new Function(this.initAfterAction)();
}else{if(a.isFunction(this.initAfterAction)){this.initAfterAction();}}}},events:{onIcoClick:function(){var b=a(this).parent();if(!b||!b.length){return;}var e=b.attr("id");var d=a.tree.fn.getNodeDataByNodeId(e);var c=("true"==(""+d["haschild"]));if(c){a.tree.fn.triggerNode(e);}},onCheckBoxClick:function(){var b=a(this).parent();
if(!b||!b.length){return;}var h=b.attr("id");var f=a.tree.fn.getTreeIdByNodeId(h);var g=a.tree.fn.getNodeDataByNodeId(h);var d=("checkbox"==a.attr(this,"type"));var i=a.data(this,"text_trigger");var c=a.attr(this,"checked");var e=g.checked;if(d){g.checked=""+(i?c:!c);}else{}a.removeData(this,"text_trigger");
if(window[f].triggerCheckBoxAction(h)){a.tree.fn.checkNode(h,true);return true;}return false;},onTextClick:function(){var b=a(this).parent();if(!b||!b.length){return;}var f=b.attr("id");var d=a.tree.fn.getTreeIdByNodeId(f);var e=a.tree.fn.getNodeDataByNodeId(f);var c=("true"==(""+e["haschild"]));if(c){if(window[d].triggerTextAction(f)){window[d].triggerNode(f);
}}else{if(window[d].triggerTextAction(f)){a.tree.fn.clickNode(f);return true;}return false;}}}};a.tree.fn.construct.prototype=a.tree.fn;}})(Wade);